FROM dockerpull.com/ubuntu:20.04

USER root
WORKDIR /root

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai

RUN apt-get update && \
    apt-get install -y \
        apt-transport-https \
        ca-certificates

RUN apt-get install -y \
        wget \
        curl \
        vim \
        build-essential \
        ninja-build \
        automake \
        autoconf \
        libtool \
        git \
        gcc \
        libssl-dev \
        bc \
        slib \
        squashfs-tools \
        android-sdk-libsparse-utils \
        android-sdk-ext4-utils \
        jq \
        cmake \
        python3-distutils \
        tcl \
        scons \
        parallel \
        openssh-client \
        tree \
        python3-dev \
        python3-pip \
        ssh \
        libncurses5 \
        pkg-config \
        lzop \
        bison \
        flex \
        rsync \
        kmod \
        cpio \
        sudo \
        fakeroot \
        dpkg-dev \
        device-tree-compiler \
        u-boot-tools \
        uuid-dev \
        libxml2-dev \
        debootstrap \
        kpartx \
        binfmt-support \
        git-lfs \
        libisl-dev \
        apt-utils \
        coreutils \
        dosfstools \
        busybox \
        tzdata \
        libncurses5-dev \
        libncursesw5-dev \
        texlive-xetex \
        texlive-latex-recommended \
        fonts-noto-cjk \
	libgflags-dev \
        locales && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python && \
    ln -s /bin/busybox /usr/bin/hexdump && \
    ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone && \
    git config --global --add safe.directory '*' && \
    locale-gen en_US.UTF-8

#COPY scripts /root
#RUN bash install_font_fandol.sh

RUN pip3 install \
        jinja2 \
        sphinx \
        sphinx-autobuild \
        sphinx_rtd_theme \
        recommonmark \
        rst2pdf \
        jieba3k \
        dfss

RUN curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo && \
    chmod a+rx /usr/local/bin/repo && \
    useradd -u 1001 ke.yi && \
    usermod -aG ke.yi ke.yi && \
    echo 'ke.yi ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers && \
    mkdir -p /home/ke.yi && \
    cp /root/.bashrc /home/ke.yi/ && \
    touch /home/ke.yi/.sudo_as_admin_successful && \
    chown -R --from=root ke.yi /home/ke.yi

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
WORKDIR /project

CMD ["bash"]

